name: Build binary

on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: go mod tidy
        working-directory: ./todo

      - name: Build binary
        run: |
          cd todo/server
          go build -o ../bin/service .