name: Linting

# Запуск при пуше в любую ветку.
on:
  push:
    branches:
      - '**'

jobs:

  lint:
    runs-on: ubuntu-latest
    
    steps:
      # Установка Go версии 1.22.
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      # Получение исходного кода из репозитория.  
      - name: Check out code
        uses: actions/checkout@v3
      
      # Установка зависимостей.
      - name: Install Dependencies
        run: go mod tidy
        working-directory: ./todo

      # Запуск линтеров.
      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          working-directory: todo
          args: --config=.golangci.yml